### ISSUE TITLE
searchNews可能会导致遍历redis所有key

### ISSUE THREAD

**Issue by xcl3721** [mikemintang/gonews#1]
searchNews可能会导致遍历redis所有key，建议redis这里加上前缀或单独使用一个redis

**Comment by mikemintang** [comment]
是的 我当初也考虑到了数据量太大 通过*key*进行遍历可能会很耗性能的问题 但是用redis存数据没有想到很好的关键词搜索方案。

**Comment by xcl3721** [comment]
可以使用这样的方法gonew_*keyword*
这样不是遍历全redis了

**Comment by mikemintang** [comment]
好的 感谢建议 我找时间改一下

**Comment by mikemintang** [comment]
已修改。https://github.com/mikemintang/gonews/commit/2700ac17820a7cf5509fb424297e808e82e92f48

**Comment by xcl3721** [comment]
赞
